name: Deploy to slides repo

on: push

jobs:
  deploy:
    if: ${{ contains(github.event.head_commit.message, '[deploy]') }}
    runs-on: ubuntu-latest
    name: copy site folder to slides repo

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Setup Node.js
      uses: actions/setup-node@master
      with:
        node-version: '22'
    
    - name: Install dependencies
      run: npm install -g reveal-md
    
    - name: Build slides
      run: cd slide/src && make build && cd ../..
    
    - name: Push update file to slides repo
      uses: dmnemec/copy_file_to_another_repo_action@3fe42250d47e0764da9de9939b151b09a26e5857
      env:
        API_TOKEN_GITHUB: ${{ secrets.GITHUB_TOKEN }}
      with:
        source_file: 'slide/site/.'
        destination_repo: 'Yusux/slides'
        destination_branch: 'main'
        destination_folder: 'ZJUSCT-HPC-Methodology-Slides'
        user_email: 'syusux@gmail.com'
        user_name: 'yusux'